version: 1.0.{build}
image: Node.js

build_script:
  - npm install
  - npm run build

deploy:
  provider: GitHub
  artifact: dist
  repository: Mikhail15011976/2.dom
  branch: main
  on:
    appveyor:
      - master
      - main